Repository kyma-project/keda-manager, pull requests merged in 2022-11, with the labels that each got.

#50 Introduce script for automated deployment on k3d
  .gitignore
  README.md
  deploy-kyma-keda-k3d.sh
  k3d-patches/busola-extensibility.yaml
  k3d-patches/busola-kyma-extension.yaml
  k3d-patches/patch-k3d-coredns.yaml
  k3d-patches/patch-k3d-module-manager-clusterrole.yaml
  k3d-patches/patch-kyma.yaml
Labels: lgtm, size/L

#49 Change Keda workloads namespace
  Makefile
  config/crd/patches/webhook_in_kedas.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/keda_namespace.yaml
  config/rbac/keda_rolebinding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controllers/keda_controller.go
  controllers/keda_controller_test.go
  module-chart/manifest/manifest.yaml
Labels: lgtm, size/XXL

#53 Cleanup makefile
  Makefile
Labels: lgtm, size/S

#52 Don't run manager when Keda is installed
  .dockerignore
  Dockerfile
  Makefile
  main.go
  pkg/keda/keda.go
  pkg/keda/keda_test.go
Labels: lgtm, size/L

#56 Make local dev
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/keda_controller.go
  deploy-kyma-keda-k3d.sh
  go.mod
  go.sum
  hack/gen-chart.sh
  hack/gen-kyma.sh
  hack/gen-mod-template.sh
  hack/get_kyma_localhost_registry_name.sh
  hack/local-template.sh
  hack/local/Makefile
  hack/local/busola/Makefile
  hack/local/busola/k3d-patches/busola-extensibility.yaml
  hack/local/busola/k3d-patches/busola-kyma-extension.yaml
  hack/local/keda/Makefile
  hack/local/keda/k3d-patches/patch-k3d-module-manager-clusterrole.yaml
  hack/local/keda/k3d-patches/patch-kyma.yaml
  hack/verify_kyma_status.sh
  k3d-patches/patch-k3d-coredns.yaml
  k3d-patches/patch-k3d-module-manager-clusterrole.yaml
Labels: lgtm, size/L

#60 Describe hack make target in readme
  README.md
Labels: lgtm, size/XS

#61 Update template channel for local development
  hack/local/keda/k3d-patches/patch-kyma.yaml
Labels: lgtm, size/XS
