Repository kyma-project/keda-manager, pull requests merged in 2022-10, with the labels that each got.

#21 change title in the readme
  README.md
Labels: lgtm, size/XS

#22 Fix codeowners
  CODEOWNERS
Labels: lgtm, size/M

#23 improve documentation
  README.md
Labels: size/M

#26 Fix makefile to accept image name passed via env variable
  operator/Makefile
Labels: lgtm, size/XS

#25 Fix documentation
  README.md
Labels: lgtm, size/L

#29 change header to another step
  README.md
Labels: lgtm, size/XS

#27 Project cleanup
  .gitignore
  Makefile
  charts/keda-operator/Chart.yaml
  charts/keda-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_kedas.operator.operator.kyma-project.io.yaml
  charts/keda-operator/templates/apps_v1_deployment_operator-controller-manager.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_operator-manager-role.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_operator-metrics-reader.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_operator-proxy-role.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_operator-manager-rolebinding.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_operator-proxy-rolebinding.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_role_operator-leader-election-role.yaml
  charts/keda-operator/templates/rbac.authorization.k8s.io_v1_rolebinding_operator-leader-election-rolebinding.yaml
  charts/keda-operator/templates/v1_configmap_operator-manager-config.yaml
  charts/keda-operator/templates/v1_namespace_operator-system.yaml
  charts/keda-operator/templates/v1_service_operator-controller-manager-metrics-service.yaml
  charts/keda-operator/templates/v1_serviceaccount_operator-controller-manager.yaml
  default.yaml
  hack/gen-mod-template.sh
  hack/local-template.sh
  mod/blobs/sha256:e3af49e853889f53d2601c8fa0904daa5e88c14bec7889518d34c794172a5ae8
  mod/component-descriptor.yaml
  operator/config/manager/kustomization.yaml
  operator/go.mod
  operator/go.sum
  template.yaml
Labels: lgtm, size/XL, hactoberfest-accepted

#31 Describe Keda Module installation on k3d
  README.md
Labels: lgtm, size/L

#30 fix kustomize download
  Makefile
Labels: lgtm, size/S

#38 fix kyma cli download
  Makefile
  hack/get_kyma_file_name.sh
Labels: lgtm, size/M

#39 fix download of keda binary
  hack/get_kyma_file_name.sh
  operator/controllers/keda_controller.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/L

#40 Bump module-manager and fix tests
  operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
  operator/controllers/keda_controller.go
  operator/controllers/keda_controller_test.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#20 Update Makefile to use changed kyma cli API
  Makefile
Labels: lgtm, size/XS, hactoberfest-accepted

#28 Update ginkgo to v2
  operator/controllers/keda_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/S

#37 Add UI Extension for scaledObjects CRs
  operator/Dockerfile
  operator/config/default/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/ui-extensions/kustomization.yaml
  operator/config/ui-extensions/scaledobjects/details
  operator/config/ui-extensions/scaledobjects/form
  operator/config/ui-extensions/scaledobjects/general
  operator/config/ui-extensions/scaledobjects/kustomization.yaml
  operator/config/ui-extensions/scaledobjects/list
  operator/config/ui-extensions/scaledobjects/presets
  operator/module-chart/manifest/manifest.yaml
Labels: lgtm, size/XXL
