Repository kyma-project/keda-manager, pull requests merged in 2022-09, with the labels that each got.

#3 Add basic scaffold for operator tests
  operator/controllers/keda_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/testdata/.helmignore
  operator/controllers/testdata/Chart.yaml
  operator/controllers/testdata/templates/01-serviceaccount.yaml
  operator/controllers/testdata/templates/_helpers.tpl
  operator/controllers/testdata/values.yaml
Labels: lgtm, area/serverless

#9 Change default image name
  operator/Makefile
Labels: lgtm, area/serverless

#6 Fix operator Dockerfile
  operator/.dockerignore
  operator/Dockerfile
Labels: lgtm, area/serverless, area/ci

#11 add test helm chart
  .idea/.gitignore
  .idea/keda-manager.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  operator/controllers/keda_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/testdata/.helmignore
  operator/controllers/testdata/Chart.yaml
  operator/controllers/testdata/templates/01-serviceaccount.yaml
  operator/controllers/testdata/templates/_helpers.tpl
  operator/controllers/testdata/values.yaml
  operator/go.sum
Labels: lgtm

#13 fix env variables in keda spec
  operator/api/v1alpha1/keda_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: lgtm

#15 Add log level, log format and time encoding values
  operator/api/v1alpha1/keda_types.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#17 fix metrics server log level type
  operator/api/v1alpha1/keda_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: lgtm, size/M

#18 fix typo in metrics server configuration
  operator/api/v1alpha1/keda_types.go
  operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: lgtm, size/XS

#12 add next test steps
  operator/api/v1alpha1/keda_types.go
  operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
  operator/controllers/keda_controller_test.go
Labels: lgtm, size/L

#19 add check if keda is deleted or deleting after deletion
  operator/controllers/keda_controller_test.go
Labels: lgtm, size/M
