Repository kyma-project/keda-manager, pull requests merged in 2022-12, with the labels that each got.

#62 Add recipes to build module on CI job
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/S

#65 fix args passing in ci script
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/S

#66 Improve ci script
  .env
  Makefile
  hack/ci/Makefile
Labels: lgtm, size/S

#71 Add frame for printed template
  hack/ci/Makefile
Labels: lgtm

#73 Add deletion-hook
  api/v1alpha1/keda_types.go
  config/samples/operator_v1alpha1_keda.yaml
  controllers/keda_controller.go
  controllers/keda_controller_test.go
  go.mod
  go.sum
Labels: lgtm, size/M

#68 improve Keda README.md
  README.md
  hack/local/keda/Makefile
Labels: documentation, lgtm, size/L, area/documentation

#77 Edit codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: lgtm, size/S

#78 Make use of busola dynamic form rendering
  config/ui-extensions/scaledobjects/form
Labels: lgtm, size/M

#79 Remove redundant coreDNS patching
  README.md
  hack/get_kyma_localhost_registry_name.sh
  hack/local/keda/Makefile
Labels: lgtm, size/M
