Repository kyma-project/keda-manager, pull requests merged in 2023-09, with the labels that each got.

#270 Bump keda to 2.11.2
  .version
  config/manager/kustomization.yaml
  keda.yaml
Labels: lgtm, size/XXL, kind/chore

#271 Bump keda module images in security context
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#273 Refactor release workflow
  .github/workflows/create-release.yaml
  scripts/check_image.sh
  scripts/create_changelog.sh
  scripts/verify-keda-status.sh
Labels: lgtm, area/ci, size/M

#274 Update metrics.yaml
  .github/workflows/metrics.yaml
Labels: lgtm, area/ci, size/XS

#275 Update create-release.yaml
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, area/ci

#276 Bump keda module images in security context2
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#277 Revert metrics changes
  .github/workflows/metrics.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/ci, size/XS

#278 Revert action name
  .github/workflows/metrics.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/ci, size/XS

#262 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L

#279 Skip DORA metrics step
  .github/workflows/create-release.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/ci, size/XS

#280 Bump Golang img version (1.21.0)
  .reuse/dep5
  Dockerfile
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#281 Bump keda menager in security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#282 Set Warning state when orphaned CRs found at deletion
  api/v1alpha1/keda_types.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/delete_resources_test.go
Labels: kind/bug, lgtm, size/S

#283 Temp Remove DORA steps from release workflow
  .github/workflows/create-release.yaml
  .github/workflows/metrics.yaml
Labels: lgtm, area/ci, size/M

#284 Bump versions in security config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#285 Implement module-config template
  .gitignore
  Makefile
  module-config-template.yaml
Labels: lgtm, size/M

#286 Restore dora step
  .github/workflows/create-release.yaml
  .github/workflows/metrics.yaml
Labels: lgtm, area/ci, size/M

#288 Include docu link and repo url in module-config template
  module-config-template.yaml
Labels: lgtm, size/XS

#289 Add darwin arm to script
  hack/get_kyma_file_name.sh
Labels: lgtm, size/XS

#290 Temporary Dora step removal
  .github/workflows/create-release.yaml
  .github/workflows/metrics.yaml
Labels: lgtm, area/ci, size/M

#291 Sec Scanner Config Bump
  sec-scanners-config.yaml
Labels: lgtm, size/XS
