Repository kyma-project/keda-manager, pull requests merged in 2023-02, with the labels that each got.

#101 Add cleanup for local development
  hack/local/keda/Makefile
  hack/local/keda/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
  hack/verify_kyma_status.sh
  pkg/reconciler/delete_resources.go
Labels: lgtm, size/S

#98 Implement safe deletion strategy
  README.md
  api/v1alpha1/keda_types.go
  pkg/reconciler/common.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/delete_resources_test.go
  pkg/reconciler/initialize.go
  pkg/reconciler/update_objects.go
  pkg/reconciler/verify.go
Labels: lgtm, size/L

#100 Keda development guide
  README.md
  docs/assets/keda-overview.drawio.svg
  docs/assets/pull_keda_module_build.png
  docs/installation-on-k3d.md
  docs/keda-configuration.md
  docs/keda-demo-application.md
  examples/keda-cpu-scaler-demo.yml
Labels: lgtm, size/XL, area/documentation

#102 Rename Keda Manager to Keda Operator
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/keda_operator_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  keda-manager.yaml
Labels: lgtm, size/L
