Repository kyma-project/keda-manager, pull requests merged in 2023-03, with the labels that each got.

#103 Keda (PR) -> Keda (Main) Upgradability test base
  Makefile
  hack/local/Makefile
  hack/local/keda/Makefile
Labels: lgtm, size/S

#106 Update Makefile to reflect new CLI changes
  Makefile
  config/manager/kustomization.yaml
  config/moduletemplates/kustomization.yaml
  hack/ci/Makefile
  hack/local/keda/Makefile
Labels: lgtm, size/S

#107 upgrade golang.org/x/net to v0.7.0
  go.mod
  go.sum
Labels: lgtm, size/S

#108 Add force flag to makefile
  hack/local/keda/Makefile
Labels: lgtm, size/XS

#117 Fix scaledObjectTerget referernce editor
  .gitignore
  config/ui-extensions/scaledobjects/form
Labels: lgtm, size/S

#121 Adjust sample keda CR
  Makefile
  README.md
  config/samples/operator_v1alpha1_keda.yaml
  docs/installation-on-k3d.md
  hack/local/keda/k3d-patches/patch-kyma.yaml
Labels: lgtm, area/documentation, size/S

#112 makefile refactor
  Makefile
  hack/ci/Makefile
  hack/common/Makefile
  hack/common/k3d-patches/patch-k3d-lifecycle-manager-clusterrole.yaml
  hack/common/k3d-patches/patch-kyma.yaml
  hack/common/verify_keda_status.sh
  hack/common/verify_kyma_status.sh
  hack/local/Makefile
  hack/local/busola/Makefile
  hack/local/keda/Makefile
Labels: lgtm, size/XL

#122 update makefile targets in doc
  README.md
Labels: lgtm, size/XS

#126 Bump keda module version to 0.0.2
  .env
Labels: lgtm, size/XS

#127 Add make target to render keda-manager manifest
  .gitignore
  Makefile
  config/manager/kustomization.yaml
  hack/ci/Makefile
Labels: lgtm, size/S

#128 Moving upgrade logic to Keda Repo
  hack/ci/Makefile
  hack/common/Makefile
Labels: lgtm, size/M
