Repository kyma-project/keda-manager, pull requests merged in 2023-12, with the labels that each got.

#317 Bump for test release
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#320 Exclude module-manifest from keda upgrade test scenario
  hack/ci/Makefile
  hack/common/Makefile
Labels: lgtm, area/ci, size/S, kind/cleanup, cla: yes

#322 Enable Markdown Link Check in the keda manager repo
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/pr-markdown-link-check.yaml
  mlc.config.json
Labels: lgtm, area/documentation, area/ci, size/M, cla: yes

#323 Update codeowners
  CODEOWNERS
Labels: lgtm, size/XS, kind/chore, cla: yes

#327 Move script to actions
  .github/workflows/create-release.yaml
  scripts/release.sh
Labels: kind/feature, lgtm, area/ci, size/S, cla: yes

#328 Fix links in keda manager repo
  CODE_OF_CONDUCT.md
  README.md
  docs/contributor/01-20-extend-ui.md
Labels: lgtm, size/S, cla: yes

#332 Adjust Keda to new content guidelines
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/01-20-extend-ui.md
  docs/contributor/02-10-management.md
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-ci-cd.md
  docs/contributor/04-20-lifecycle-management.md
  docs/contributor/04-30-project-structure.md
  docs/user/01-20-configuration.md
  docs/user/04-10-footprint.md
  docs/user/04-20-demo-applications.md
  docs/user/05-01-conditions.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: lgtm, size/M, cla: yes

#335 Copy Prometheus scaler example to Keda repo
  docs/user/04-20-demo-applications.md
  docs/user/examples/scale-to-zero-with-keda/README.md
  docs/user/examples/scale-to-zero-with-keda/assets/scaling-scenario.drawio
  docs/user/examples/scale-to-zero-with-keda/assets/scaling-scenario.png
  docs/user/examples/scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  docs/user/examples/scale-to-zero-with-keda/k8s-resources/peer-authentication.yaml
  docs/user/examples/scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
  docs/user/examples/scale-to-zero-with-keda/src/http-proxy-fn/handler.js
  docs/user/examples/scale-to-zero-with-keda/src/http-proxy-fn/package.json
  docs/user/examples/scale-to-zero-with-keda/src/scalable-worker-fn/handler.js
  docs/user/examples/scale-to-zero-with-keda/src/scalable-worker-fn/package.json
Labels: lgtm, size/L, area/documentation, cla: yes

#337 Fix bug in Demo Applications
  docs/user/04-20-demo-applications.md
Labels: lgtm, size/XS, cla: yes
