Repository kyma-project/keda-manager, pull requests merged in 2023-07, with the labels that each got.

#222 Implement disclaimer for all applied objects
  pkg/annotation/disclaimer.go
  pkg/annotation/disclaimer_test.go
  pkg/reconciler/apply.go
Labels: lgtm, size/M

#224 Bump image
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#225 Prepare makefiles for new test-infra dind image
  hack/common/Makefile
Labels: lgtm, size/XS

#226 Trigger post module build
  .env
Labels: lgtm, size/XS

#228 check if tag in .env is the same as provided in github release
  .env
  .github/workflows/create-release.yaml
  .version
  Makefile
  hack/ci/Makefile
  hack/common/Makefile
  scripts/check_release_tag.sh
Labels: lgtm, area/ci, size/M

#233 Bump image and fix image checker
  scripts/check_image.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#229 fix broken links
  docs/user/04-20-demo-applications.md
Labels: lgtm, size/XS

#234 Check also the date in the image
  scripts/check_image.sh
Labels: lgtm, size/S

#235 Improve err msg and bump image
  scripts/check_release_tag.sh
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#236 Configure UI for Keda CR
  config/ui-extensions/kedas/details
  config/ui-extensions/kedas/form
  config/ui-extensions/kedas/general
  config/ui-extensions/kedas/kustomization.yaml
  config/ui-extensions/kedas/list
  config/ui-extensions/kustomization.yaml
Labels: kind/feature, lgtm, size/L

#238 Bump keda version (v2.11.1)
  keda.yaml
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XL

#239 Upgate sec-scanner-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#241 Remove istio side-car from keda workloads
  keda.yaml
Labels: lgtm, size/XS

#243 Upgate sec-scanner-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#244 Update create-release.yaml
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, size/XS

#246 Add status badge
  README.md
Labels: lgtm, size/XS

#248 Update README.md
  README.md
Labels: lgtm, area/documentation, size/S

#249 Update README.md
  README.md
Labels: lgtm, size/XS
