Repository kyma-project/keda-manager, pull requests merged in 2023-08, with the labels that each got.

#251 change links to relative ones
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/02-10-management.md
  docs/contributor/04-20-lifecycle-management.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, lgtm, area/documentation, size/M

#252 speed up tests
  controllers/suite_test.go
Labels: lgtm, size/S

#253 Remove Labels
  hack/common/Makefile
Labels: lgtm, size/XS

#254 Add template to release assets
  scripts/release.sh
Labels: lgtm, size/XS, kind/chore

#255 Unifying names for release assets
  .gitignore
  Makefile
  config/samples/keda_default_cr.yaml
  docs/contributor/02-10-management.md
  hack/ci/Makefile
  hack/common/Makefile
  scripts/release.sh
Labels: lgtm, area/serverless, kind/cleanup, size/M

#263 Add DORA Metrics collector to Keda Release pipeline
  .github/workflows/create-release.yaml
  .github/workflows/metrics.yaml
Labels: kind/feature, lgtm, area/ci, size/M

#264 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#268 Update security scanner exclusions
  sec-scanners-config.yaml
Labels: lgtm, size/XS
