Repository kyma-project/keda-manager, pull requests merged in 2023-11, with the labels that each got.

#303 Use latest Keda version v2.12.0
  .version
  Dockerfile
  keda.yaml
  sec-scanners-config.yaml
Labels: kind/feature, lgtm

#304 Drop v prefix from version format
  scripts/check_release_tag.sh
Labels: lgtm, kind/cleanup, size/XS

#305 Include version 1.0.0 in scanning
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#306 Use latest tags in sec-scanners-config on main
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, area/security, size/XS

#307 Don't use sec-scanners-config to build moduletemplate on pre/post submit
  Makefile
  module-config-template.yaml
Labels: kind/feature, lgtm, area/security, size/XS

#308 Use sec-scanners-config during the release
  Makefile
  scripts/release.sh
  sec-scanners-config-local.yaml
Labels: kind/bug, lgtm, area/security, size/S

#309 add configuration for golangci-lint
  .golangci.yaml
Labels: lgtm, area/ci, size/S, kind/cleanup

#310 Bump golang 1.21.4
  .version
  Dockerfile
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#311 Bump keda-manager in security scanners conf
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#312 Release keda 1.0.2
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#313 Make sure latest manager image is scanned on main group
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore

#314 Use branch name instead of latest word
  sec-scanners-config.yaml
Labels: lgtm, area/ci, kind/cleanup, size/XS, cla: yes
