Repository kyma-project/keda-manager, pull requests merged in 2023-06, with the labels that each got.

#185 add deleted condition
  api/v1alpha1/keda_types.go
  config/rbac/role.yaml
  controllers/keda_controller_rbacs.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/delete_resources_test.go
  pkg/reconciler/emmit_event.go
  pkg/reconciler/fsm.go
Labels: lgtm, size/L

#187 Remove keda after integration test finish
  hack/ci/Makefile
Labels: lgtm, kind/cleanup, size/XS

#189 Run Tidy on Gomod
  go.mod
Labels: lgtm, size/XS

#192 Bump go version in workflow
  .github/workflows/run-unit-tests-reusable.yaml
Labels: lgtm, area/ci, size/XS

#191 Add document on Keda conditions
  docs/user/05-01-conditions.md
Labels: lgtm, area/documentation, size/S

#194 Move tests to separate file outside of release.sh
  scripts/release.sh
Labels: lgtm, size/S

#195 Bump keda-manager version
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#197 Do not save kyma-bot commits in the changelog
  scripts/create_changelog.sh
Labels: lgtm, size/XS

#200 Add module tests sub-workflow to release workflow
  .github/workflows/create-release.yaml
  .github/workflows/run-module-tests.yaml
  .github/workflows/run-unit-tests.yaml
  scripts/await_artifacts.sh
  scripts/k3s-setup.sh
  scripts/module_tests.sh
  scripts/yaml/registries.yaml
Labels: lgtm, size/L, area/ci

#201 Add permission to script files
  scripts/await_artifacts.sh
  scripts/k3s-setup.sh
Labels: lgtm, size/XS

#202 Fix typo
  scripts/await_artifacts.sh
  scripts/module_tests.sh
Labels: lgtm, size/M

#203 Skip waiting for artifacts
  .github/workflows/run-module-tests.yaml
  scripts/await_artifacts.sh
Labels: lgtm, area/ci, size/M

#199 Fix integration tests
  hack/common/Makefile
Labels: kind/bug, lgtm, size/XS

#204 GHActions step that verifies the status of Post Jobs for Keda Manager
  .github/workflows/create-release.yaml
  .github/workflows/run-module-tests.yaml
  scripts/k3s-setup.sh
  scripts/module_tests.sh
  scripts/verify-keda-status.sh
  scripts/yaml/registries.yaml
Labels: lgtm, size/L, area/ci

#205 Add a checkout step for verify action
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, size/XS

#207 Add debug message to verify step in GH actions
  scripts/verify-keda-status.sh
Labels: lgtm, size/XS

#208 Change credentials used in github actions
  scripts/verify-keda-status.sh
Labels: lgtm, size/XS

#209 Removed token from workflow
  .github/workflows/create-release.yaml
  scripts/verify-keda-status.sh
Labels: lgtm, area/ci, size/XS

#211 Bump golang-runtime to 1.20.5
  Dockerfile
Labels: lgtm, size/XS

#212 Fix Mend exclude field in sec config
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#156 Adjust Keda docs according to the documentation requirements
  README.md
  docs/OWNERS
  docs/README.md
  docs/assets/keda-lm-overview.drawio.svg
  docs/assets/keda-overview.drawio.svg
  docs/assets/prow_job_status.png
  docs/assets/pull_keda_module_build.png
  docs/contributor/01-10-installation.md
  docs/contributor/01-20-extend-ui.md
  docs/contributor/02-10-management.md
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-ci-cd.md
  docs/contributor/04-20-lifecycle-management.md
  docs/contributor/04-30-project-structure.md
  docs/user/01-20-configuration.md
  docs/user/04-10-footprint.md
  docs/user/04-20-demo-application.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: lgtm, size/L, area/documentation

#213 Link Advanced Keda Example
  docs/assets/scaling-scenario.png
  docs/user/04-20-demo-applications.md
  docs/user/_sidebar.md
  keda.yaml
Labels: lgtm, area/documentation, size/S

#214 Bump Keda Manager Version before release
  .env
  config/manager/kustomization.yaml
  docs/user/README.md
Labels: lgtm, size/XS

#215 Updated the security scanner config to include newest release
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#216 Update _sidebar.md
  docs/user/_sidebar.md
Labels: lgtm, size/XS

#219 fixx typo
  README.md
Labels: lgtm, size/XS

#220 fix demo applications link
  docs/contributor/02-10-management.md
Labels: lgtm, size/XS

#221 Prepare for Keda Patch
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS
