Repository kyma-project/keda-manager, pull requests merged in 2023-01, with the labels that each got.

#72 Remove module-template-push target
  Makefile
Labels: lgtm, size/S

#86 Remove initializing status state
  api/v1alpha1/keda_types.go
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  pkg/reconciler/initialize.go
Labels: lgtm, size/S

#91 Add integration-test mock
  Makefile
  hack/ci/Makefile
Labels: lgtm, area/serverless, size/S

#85 Implement integration smoke tests
  hack/ci/Makefile
  test/deployment/create.go
  test/go.mod
  test/go.sum
  test/hpa/verify.go
  test/logger/logger.go
  test/main.go
  test/namespace/create.go
  test/namespace/delete.go
  test/scaledobject/create.go
  test/scaledobject/delete.go
  test/scaledobject/verify.go
  test/utils/client.go
  test/utils/retry.go
  test/utils/types.go
Labels: lgtm, size/XL

#93 Implement safe deletion strategy
  README.md
  hack/verify_kyma_status.sh
  pkg/reconciler/delete_resources.go
  pkg/reconciler/delete_resources_test.go
Labels: lgtm, size/L, area/serverless

#95 Add MK to codeowners
  CODEOWNERS
Labels: lgtm, size/XS

#94 Introduce stubs for make targets composing E2E release process
  Makefile
Labels: lgtm, size/S

#96 Fix keda module name prefix
  Makefile
  README.md
  config/default/kustomization.yaml
Labels: lgtm, size/XS

#97 Fix api versions for scaled object targets in the Form view
  config/ui-extensions/scaledobjects/form
  config/ui-extensions/scaledobjects/general
Labels: lgtm, size/XS
