Repository kyma-project/keda-manager, pull requests merged in 2023-04, with the labels that each got.

#132 Cleanup orphaned leases and unused leader-election config
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/manager/keda_operator_config.yaml
  config/manager/kustomization.yaml
  pkg/reconciler/delete_resources.go
Labels: lgtm, size/M

#131 Use Keda v2.10.0
  Makefile
  PROJECT
  README.md
  api/v1alpha1/keda_types.go
  config/crd/patches/cainjection_in_kedas.yaml
  config/crd/patches/webhook_in_kedas.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controllers/keda_controller_rbacs.go
  controllers/keda_controller_test.go
  docs/installation-on-k3d.md
  hack/common/Makefile
  keda.yaml
  pkg/reconciler/common.go
  pkg/reconciler/fsm.go
  pkg/reconciler/update_objects.go
  pkg/reconciler/verify.go
  test/deployment/create.go
Labels: lgtm, size/XXL, area/documentation

#136 Bump version v0.0.3
  .env
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  hack/common/Makefile
Labels: lgtm, size/XS

#138 Upgrade Job Hotfix
  hack/ci/Makefile
Labels: lgtm, size/XS

#135 Add Security Config to Keda Manager
  sec-scanners-config.yaml
Labels: lgtm, size/S

#139 Add priting to make target
  hack/common/Makefile
Labels: lgtm, size/XS

#141 Improve events message
  pkg/reconciler/emmit_event.go
  pkg/reconciler/update_status.go
Labels: lgtm, kind/cleanup, size/XS

#142 Don't update condition while keda CR is deleted
  api/v1alpha1/keda_types.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/delete_resources_test.go
  pkg/reconciler/emmit_event.go
Labels: lgtm, size/L

#145 Bumpe version to v0.0.4
  .env
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  hack/common/Makefile
Labels: lgtm, size/XS

#148 Makefile cleanup
  README.md
  config/default/kustomization.yaml
  hack/common/Makefile
  hack/local/Makefile
  hack/local/busola/Makefile
  hack/local/busola/k3d-patches/busola-extensibility.yaml
  hack/local/busola/k3d-patches/busola-kyma-extension.yaml
Labels: lgtm, size/L

#149 Use latest golang in builder image
  Dockerfile
Labels: lgtm, size/XS
