Repository kyma-project/keda-manager, pull requests merged in 2023-10, with the labels that each got.

#292 Unify fqdn for keda module
  Makefile
Labels: lgtm, size/XS

#293 Change workflow to match Sec_scanner_config with new release version
  .github/workflows/create-release.yaml
  scripts/check_image.sh
Labels: lgtm, area/ci, size/S

#294 Bump golang
  Dockerfile
Labels: lgtm, size/XS

#295 Prepare new release
  .version
Labels: lgtm, size/XS

#296 Bump image
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#297 Use correct tag for release
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#299 Add more release logs
  scripts/release.sh
Labels: lgtm, size/S

#301 Align name of the default keda CR manifest
  config/samples/keda-default-cr.yaml
  docs/contributor/02-10-management.md
  hack/common/Makefile
  module-config-template.yaml
  scripts/release.sh
Labels: lgtm, size/S
