Repository kyma-project/keda-manager, pull requests merged in 2023-05, with the labels that each got.

#150 Bump golang-runtime to 1.20.4
  Dockerfile
Labels: lgtm, size/XS

#151 Remove helm escaping in UI config
  config/ui-extensions/scaledobjects/general
Labels: lgtm, size/XS

#154 Add beta label to test keda as beta module
  hack/common/Makefile
Labels: lgtm, size/XS

#147 Update and clean up the Keda docs
  README.md
  docs/README.md
  docs/assets/keda-overview.drawio.svg
  docs/assets/prow_job_status.png
  docs/installation-on-k3d.md
  docs/keda-demo-application.md
  docs/keda-installation.md
  docs/keda-management.md
Labels: lgtm, size/XL, area/documentation

#152 Bump Keda version to 2.10.1
  .env
  config/manager/kustomization.yaml
  keda.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/L

#159 Assume Deployment as a default scaledTargetRef.kind
  config/ui-extensions/scaledobjects/details
  config/ui-extensions/scaledobjects/list
Labels: kind/bug, lgtm, size/XS

#158 Use keda images synced into europe-docker.pkg.dev/kyma-project
  keda.yaml
  sec-scanners-config.yaml
Labels: lgtm, kind/cleanup

#162 GitHub actions release
  .github/workflows/create-release.yaml
  .github/workflows/run-unit-tests-reusable.yaml
  scripts/await_artifacts.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_release.sh
  scripts/release.sh
Labels: lgtm, size/L, area/ci

#163 Bump Version before Release
  .env
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#164 Fix step name for Actions
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, area/ci, size/XS

#165 Add permissions to script generating changelog
  scripts/create_changelog.sh
Labels: kind/bug, lgtm, size/XS

#166 Add permissions to script publishing the release #165
  scripts/publish_release.sh
  scripts/release.sh
Labels: kind/bug, lgtm, size/XS

#167 Build module for release process
  scripts/release.sh
Labels: kind/bug, lgtm, size/XS

#168 Change command used for release
  scripts/release.sh
Labels: kind/bug, lgtm, size/XS

#171 Add script for creating assets
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, size/S

#176 Fix release_id variable
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, size/XS

#177 Wait for keda-manager.yaml
  scripts/await_artifacts.sh
  scripts/release.sh
Labels: lgtm, size/XS

#175 Define resources for keda-manager workload
  config/manager/manager.yaml
Labels: kind/feature, lgtm, size/XS

#181 Regenerate config
  Makefile
  config/crd/bases/operator.kyma-project.io_kedas.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: lgtm, size/S

#184 Bump keda-manager image in sec scanner config
  sec-scanners-config.yaml
Labels: lgtm, size/XS
