Repository kyma-project/keda-manager, pull requests merged in 2024-05, with the labels that each got.

#430 Create the `rebase` action
  .github/actions/rebase/action.yaml
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/keda-verify.yml
  .github/workflows/pr-markdown-link-check.yaml
  .github/workflows/pull-gitleaks.yaml
Labels: lgtm, area/ci, size/M, kind/chore, cla: yes

#431 Cover case when the `main` branch exists
  .github/actions/rebase/action.yaml
Labels: kind/bug, lgtm, size/XS, cla: yes, area/keda-manager

#433 Fix bug when updating main
  .github/actions/rebase/action.yaml
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes, area/keda-manager

#432 Gh actions cleanup
  .github/actions/create-single-cluster/action.yaml
  .github/actions/setup-go/action.yaml
  .github/workflows/create-release.yaml
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/gitleaks.yaml
  .github/workflows/keda-verify.yml
  .github/workflows/markdown.yaml
Labels: lgtm, size/L, area/ci, kind/cleanup, cla: yes, area/keda-manager

#434 Gh actions split verify
  .github/actions/create-k3d-cluster/action.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/keda-verify.yml
  .github/workflows/lint.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/upgrade-tests.yaml
  docs/contributor/04-10-ci-cd.md
  docs/contributor/04-10-testing-strategy.md
Labels: lgtm, size/L, area/ci, kind/cleanup, cla: yes, area/keda-manager

#435 adjust testing strategy
  .github/workflows/integration-tests.yaml
  docs/contributor/04-10-testing-strategy.md
Labels: lgtm, area/documentation, area/ci, size/S, kind/cleanup, cla: yes, area/keda-manager

#436 extract version of go to input in action setup-go
  .github/actions/setup-go/action.yaml
Labels: lgtm, area/ci, kind/cleanup, size/XS, cla: yes, area/keda-manager

#440 Unify Keda CR description in Kyma dashboard
  config/ui-extensions/kedas/general
Labels: documentation, lgtm, size/XS, cla: yes

#441 Unify Keda CR description
  config/ui-extensions/kedas/general
Labels: lgtm, size/XS, cla: yes

#444 Bump keda to 2.14
  keda.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XXL, kind/chore, cla: yes
