Repository kyma-project/keda-manager, pull requests merged in 2024-12, with the labels that each got.

#549 Use tf GH actions from terraform-module
  .github/actions/setup-btp/action.yaml
  .github/actions/setup-kyma/action.yaml
  .github/actions/setup-terraform/action.yaml
  .github/workflows/_integration-tests.yaml
  test/btp/README.md
  test/btp/hack/Makefile
  test/btp/hack/get_btp_file_name.sh
  test/btp/hack/set-tf-envs.sh
  test/btp/tf/main.tf
  test/btp/tf/variables.tf
Labels: lgtm, size/L, area/ci, cla: yes

#550 Bump tf modules to include module json parsing
  .github/workflows/_integration-tests.yaml
Labels: lgtm, area/ci, size/XS, cla: yes

#551 Automate Keda module promotion flow
  .github/workflows/promote-to-release-channel.yaml
  Makefile
  module-config-template.yaml
Labels: lgtm, size/L, area/ci, cla: yes

#554 Bump base go image
  Dockerfile
Labels: size/XS, cla: yes

#561 bump keda images
  external-images.yaml
Labels: size/XS, cla: yes
