Repository kyma-project/keda-manager, pull requests merged in 2024-03, with the labels that each got.

#374 Improve the Keda module testing strategy doc
  docs/contributor/04-10-ci-cd.md
Labels: lgtm, area/documentation, size/S, cla: yes

#373 Redis scaler example
  .gitignore
  examples/redis-scaler/Makefile
  examples/redis-scaler/README.md
  examples/redis-scaler/assets/scenario.drawio
  examples/redis-scaler/assets/scenario.drawio.svg
  examples/redis-scaler/k8s-resources/emitter-fn.yaml
  examples/redis-scaler/k8s-resources/kustomization.yaml
  examples/redis-scaler/k8s-resources/scaled-job.yaml
  examples/redis-scaler/src/emitter-fn/config.yaml
  examples/redis-scaler/src/emitter-fn/handler.js
  examples/redis-scaler/src/emitter-fn/package.json
  examples/redis-scaler/src/receiver-job/Dockerfile
  examples/redis-scaler/src/receiver-job/app.js
  examples/redis-scaler/src/receiver-job/package.json
Labels: lgtm, size/L, cla: yes

#376 Apply Markdown linting in the Keda Manager repo
  .markdownlint.yaml
  .markdownlintignore
  CONTRIBUTING.md
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/01-20-extend-ui.md
  docs/contributor/02-10-management.md
  docs/contributor/03-10-scripts-not-working.md
  docs/contributor/04-10-ci-cd.md
  docs/contributor/04-20-lifecycle-management.md
  docs/contributor/04-30-project-structure.md
  docs/user/01-20-configuration.md
  docs/user/04-10-footprint.md
  docs/user/04-20-demo-applications.md
  docs/user/05-01-conditions.md
  docs/user/README.md
  examples/scale-to-zero-with-keda/README.md
  heading_capitalization.js
Labels: lgtm, size/L, area/documentation, cla: yes

#386 Fix failing workflow
  .github/dependabot.yml
  .github/workflows/keda-verify.yml
Labels: lgtm, area/ci, size/S, cla: yes

#388 Remove module manager dependency
  controllers/keda_controller_test.go
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#391 Bump controller-gen
  Makefile
  config/crd/bases/operator.kyma-project.io_kedas.yaml
  config/rbac/role.yaml
  inflections.json
Labels: lgtm, size/L, cla: yes

#392 Fix release image path
  Makefile
Labels: lgtm, size/XS, cla: yes
