Repository kyma-project/keda-manager, pull requests merged in 2024-04, with the labels that each got.

#394 Bump k8s to 1.27
  .github/workflows/keda-verify.yml
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kedas.yaml
  controllers/keda_controller.go
  go.mod
  go.sum
  pkg/reconciler/apply.go
  test/go.mod
  test/go.sum
  test/scaledobject/create.go
Labels: lgtm, size/XL, area/ci, cla: yes

#397 Upgrade project go version
  .github/workflows/keda-verify.yml
  go.mod
  go.sum
  pkg/reconciler/served_filter_test.go
Labels: lgtm, area/ci, size/M, cla: yes

#399 Use single go.mod file
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, size/XXL, cla: yes

#406 Add Halamix2 to codeowners
  CODEOWNERS
Labels: lgtm, size/XS, cla: yes

#398 Enable gitleaks check
  .github/workflows/pull-gitleaks.yaml
Labels: lgtm, area/ci, size/S, cla: yes

#409 Remove differences between keda-manager and serverless repos
  .github/scripts/release.sh
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, kind/cleanup, size/XS, cla: yes

#408 bump github.com/kedacore/keda/v2
  go.mod
  go.sum
  main.go
  test/utils/types.go
Labels: lgtm, size/XXL, cla: yes

#417 Disable md checks for shields and reuse links
  mlc.config.json
Labels: kind/bug, lgtm, area/documentation, area/ci, size/M, cla: yes

#421 Test with k8s v1.29.3
  .github/workflows/keda-verify.yml
Labels: lgtm, size/XS, kind/chore, cla: yes

#423 fix image building under ADO
  Dockerfile
Labels: lgtm, size/XS, cla: yes

#422 Bump controller-runtime
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes
