Repository kyma-project/keda-manager, pull requests merged in 2024-06, with the labels that each got.

#446 disable running markdown checker on pull and enable on push
  .github/workflows/markdown.yaml
  .mlc.config.json
  docs/contributor/04-10-testing-strategy.md
Labels: lgtm, area/ci, size/S, kind/cleanup, cla: yes

#450 Add Keda priority class
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/priority-class/keda_priority_class.yaml
  config/priority-class/kustomization.yaml
Labels: lgtm, size/S, cla: yes

#452 Fix link to mlc config
  docs/contributor/04-10-testing-strategy.md
Labels: lgtm, size/XS, cla: yes

#451 Use consistent labels
  config/default/kustomization.yaml
  config/ui-extensions/kedas/kustomization.yaml
Labels: lgtm, size/S, cla: yes

#454 restore old label selector
  config/default/kustomization.yaml
  config/manager/manager.yaml
Labels: lgtm, size/S, cla: yes

#455 Add priority class for managed keda workloads
  config/manager/manager.yaml
  config/priority-class/keda_priority_class.yaml
  pkg/reconciler/fsm.go
  pkg/reconciler/update_objects.go
Labels: lgtm, size/M, cla: yes
