Repository kyma-project/keda-manager, pull requests merged in 2024-10, with the labels that each got.

#512 feat: Add proper categories for keda CRDs
  api/v1alpha1/keda_types.go
  config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: kind/feature, size/XS, cla: yes

#513 feat: Add proper categories for CRDs
  api/v1alpha1/keda_types.go
  config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: lgtm, size/XS, cla: yes

#514 Set fixed lint action version
  .github/workflows/lint.yaml
Labels: lgtm, area/ci, size/XS, kind/chore, cla: yes

#517 normalize github script names
  .github/scripts/create-changelog.sh
  .github/scripts/create-draft-release.sh
  .github/scripts/publish-release.sh
  .github/workflows/create-release.yaml
Labels: area/ci, size/XS, cla: yes

#520 Fix link checker version
  .github/workflows/markdown.yaml
Labels: area/ci, size/S, cla: yes

#516 Btp integration test
  .github/actions/setup-btp/action.yaml
  .github/actions/setup-kyma/action.yaml
  .github/actions/setup-terraform/action.yaml
  .github/workflows/_integration-tests.yaml
  .github/workflows/create-release.yaml
  test/btp/README.md
  test/btp/hack/Makefile
  test/btp/hack/get_btp_file_name.sh
  test/btp/hack/set-tf-envs.sh
  test/btp/tf/main.tf
  test/btp/tf/variables.tf
  test/main.go
Labels: lgtm, size/L, area/ci, cla: yes

#522 Reduce requested resources
  api/v1alpha1/keda_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kedas.yaml
  config/samples/keda-default-cr.yaml
  config/ui-extensions/kedas/details
  config/ui-extensions/kedas/form
  docs/contributor/02-10-management.md
  docs/user/01-20-configuration.md
  pkg/reconciler/update_objects.go
Labels: lgtm, size/L, cla: yes

#523 Add image syncer job
  .github/workflows/sync-external-images.yaml
Labels: area/ci, size/S, cla: yes

#524 Add image syncer config
  external-images.yaml
Labels: lgtm, size/XS, cla: yes

#525 Fix status check
  hack/common/verify_keda_status.sh
Labels: lgtm, size/S, cla: yes

#527 Remove checking if hpa was deleted from integration test scenario
  test/main.go
Labels: lgtm, size/XS, cla: yes
