Repository kyma-project/keda-manager, pull requests merged in 2024-11, with the labels that each got.

#533 Bump CRD Version during release
  .github/workflows/create-release.yaml
  hack/replace_keda_crd_version.sh
Labels: lgtm, area/ci, size/S, cla: yes

#532 Re-enable Dora insights binary
  .github/workflows/create-release.yaml
  .github/workflows/metrics.yaml
Labels: area/ci, size/M, cla: yes

#534 Fix Dora insights binary download
  .github/workflows/metrics.yaml
Labels: lgtm, area/ci, size/XS, cla: yes

#535 test dora download
  .github/workflows/metrics-test.yaml
  .github/workflows/test-dora-download.yaml
Labels: lgtm, area/ci, size/M, cla: yes

#536 test dora download
  .github/workflows/metrics-test.yaml
Labels: lgtm, area/ci, size/XS, cla: yes

#537 test dora download
  .github/workflows/_metrics.yaml
  .github/workflows/create-release.yaml
  .github/workflows/metrics-test.yaml
  .github/workflows/metrics.yaml
  .github/workflows/test-dora-download.yaml
Labels: lgtm, area/ci, size/M, cla: yes

#538 Cleanup dora steps in workflows
  .github/workflows/_metrics.yaml
  .github/workflows/test-dora-download.yaml
Labels: lgtm, area/ci, size/M, cla: yes

#539 Change deployment target for Dora stats
  .github/workflows/_metrics.yaml
Labels: lgtm, area/ci, size/XS, cla: yes

#545 Bump k8s version
  .github/actions/create-k3d-cluster/action.yaml
  Makefile
  config/crd/bases/operator.kyma-project.io_kedas.yaml
Labels: lgtm, area/ci, size/S, cla: yes

#544 Bump Go dependencies
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes
