Repository kyma-project/keda-manager, pull requests merged in 2024-09, with the labels that each got.

#490 Update contributing.md
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#491 docs: Add mandatory sections to README.md
  README.md
Labels: lgtm, size/S, cla: yes

#492 Bump keda to 2.15.1
  keda.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XL, cla: yes

#495 Add basic label test
  go.mod
  go.sum
  pkg/reconciler/fsm_test.go
Labels: lgtm, size/M, cla: yes

#497 Use go.mod go version in actions
  .github/actions/setup-go/action.yaml
Labels: lgtm, area/ci, size/S, cla: yes

#498 Unify linter config
  .golangci.yaml
  test/hpa/verify.go
Labels: size/S, cla: yes

#499 Lint tests
  .golangci.yaml
Labels: lgtm, size/XS, cla: yes

#502 Fix controller-gen version detection
  Makefile
Labels: lgtm, size/XS, cla: yes

#504 Support istio sidecar injection
  api/v1alpha1/keda_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kedas.yaml
  pkg/reconciler/fsm.go
  pkg/reconciler/fsm_test.go
  pkg/reconciler/update_objects.go
Labels: kind/feature, size/L, cla: yes, area/keda-manager

#506 Add Istio Sidecar configuration to the UI panel
  config/ui-extensions/kedas/details
  config/ui-extensions/kedas/form
Labels: size/S, kind/chore, area/busola, cla: yes, area/keda-manager

#505 Update docs about sidecar injection
  docs/user/01-20-configuration.md
Labels: area/documentation, size/S, kind/chore, cla: yes, area/keda-manager

#508 Update the Keda module docs based on the help portal deliverables
  docs/assets/keda_architecture.svg
  docs/user/01-20-configuration.md
  docs/user/README.md
Labels: lgtm, size/S, cla: yes

#510 Improve istio injection summary
  config/ui-extensions/kedas/details
Labels: kind/feature, lgtm, size/XS, cla: yes, area/keda-manager
