Repository kyma-project/keda-manager, pull requests merged in 2024-01, with the labels that each got.

#341 Remove secrets and configmaps from the cache
  main.go
Labels: kind/feature, lgtm, size/XS, cla: yes

#342 Automatic bump in sec-scanners-config in the release process
  .github/scripts/upgrade-sec-scanners-config.sh
  .github/workflows/create-release.yaml
Labels: kind/feature, lgtm, area/ci, size/M, cla: yes

#343 Remove step checking main images in the sec-scanners-config.yaml
  .github/scripts/check_image.sh
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#344 Bump golang to 1.21.5
  Dockerfile
Labels: lgtm, size/XS, kind/chore, cla: yes

#346 Use the `gh-cli` app to verify job statuses
  .github/scripts/verify-keda-jobs-status.sh
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#347 Add missing `GH_TOKEN` env
  .github/workflows/create-release.yaml
Labels: kind/bug, lgtm, area/ci, size/XS, cla: yes

#348 Move status badge to status subcategory
  README.md
Labels: lgtm, area/documentation, kind/cleanup, cla: yes

#345 Adjust Prometheus example diagram and move the example to the root folder
  docs/user/examples/scale-to-zero-with-keda/assets/scaling-scenario.drawio
  docs/user/examples/scale-to-zero-with-keda/assets/scaling-scenario.png
  examples/scale-to-zero-with-keda/README.md
  examples/scale-to-zero-with-keda/assets/scaling-scenario.drawio
  examples/scale-to-zero-with-keda/assets/scaling-scenario.png
  examples/scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
  examples/scale-to-zero-with-keda/k8s-resources/peer-authentication.yaml
  examples/scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
  examples/scale-to-zero-with-keda/src/http-proxy-fn/handler.js
  examples/scale-to-zero-with-keda/src/http-proxy-fn/package.json
  examples/scale-to-zero-with-keda/src/scalable-worker-fn/handler.js
  examples/scale-to-zero-with-keda/src/scalable-worker-fn/package.json
Labels: lgtm, size/L, cla: yes

#350 Enable linting in GH Actions
  .github/workflows/keda-verify.yml
Labels: lgtm, area/ci, size/S, cla: yes

#351 Enable unit tests in GH Actions
  .github/workflows/keda-verify.yml
Labels: lgtm, area/ci, size/XS, cla: yes

#354 Remove installation instructions mentioning moduletemplate
  docs/contributor/01-10-installation.md
Labels: documentation, lgtm, size/L, kind/cleanup, cla: yes

#352 Enable upgrade tests in GH Actions
  .github/workflows/keda-verify.yml
  hack/ci/Makefile
Labels: lgtm, area/ci, size/M, cla: yes

#349 enable dependabot for actions & dockerfile
  .github/dependabot.yml
Labels: lgtm, area/ci, size/S, cla: yes

#353 Enable integration tests in GH Actions
  .github/workflows/keda-verify.yml
  hack/ci/Makefile
  hack/common/Makefile
Labels: lgtm, area/ci, size/M, cla: yes

#357 Fix upgrade GH Action
  .github/workflows/keda-verify.yml
Labels: lgtm, area/ci, size/XS, cla: yes

#358 Don't fail on namespace creation
  hack/ci/Makefile
  hack/common/Makefile
Labels: lgtm, size/XS, cla: yes

#360 Remove links to non-existing sections
  docs/contributor/01-10-installation.md
Labels: lgtm, size/XS, cla: yes
