Repository kyma-project/keda-manager, pull requests merged in 2024-02, with the labels that each got.

#361 Add resources check to keda jobs
  hack/common/Makefile
Labels: kind/feature, lgtm, area/ci, size/S, cla: yes

#365 remove makefile targets with lifecycle manager
  hack/ci/Makefile
  hack/common/Makefile
  hack/local/Makefile
Labels: lgtm, kind/cleanup, size/M, cla: yes

#367 adjust documentation after removing makefile targets for lifecycle ma…
  docs/contributor/01-10-installation.md
  docs/contributor/04-10-ci-cd.md
Labels: lgtm, size/S, kind/cleanup, cla: yes

#366 rename makefile targets "without lm"
  hack/ci/Makefile
  hack/common/Makefile
  hack/local/Makefile
Labels: lgtm, kind/cleanup, size/M, cla: yes

#368 Makefile remove unused
  hack/ci/Makefile
  hack/common/Makefile
  hack/common/verify_kyma_status.sh
Labels: lgtm, kind/cleanup, size/M, cla: yes

#371 Test keda module on k8s 1.28.6
  .github/workflows/keda-verify.yml
Labels: lgtm, kind/chore, cla: yes

#372 Change on cluster to in cluster
  docs/contributor/01-10-installation.md
  docs/contributor/02-10-management.md
  docs/contributor/04-10-ci-cd.md
Labels: lgtm, size/S, cla: yes
