Repository kyma-project/keda-manager, pull requests merged in 2024-07, with the labels that each got.

#459 Add GHA build workflows
  .github/workflows/keda-build-pull.yaml
  .github/workflows/keda-build-push.yaml
  .github/workflows/keda-build-release.yaml
Labels: lgtm, area/ci, size/M, cla: yes

#460 Add branch name tag to push image
  .github/workflows/keda-build-push.yaml
Labels: lgtm, area/ci, size/S, cla: yes

#461 Fix tag creation
  .github/workflows/keda-build-push.yaml
Labels: lgtm, area/ci, size/XS, cla: yes

#462 Remove duplicated workflows
  .github/workflows/build-pull.yaml
  .github/workflows/build-push-release.yaml
  .github/workflows/keda-build-push.yaml
Labels: lgtm, area/ci, size/S, cla: yes

#463 Use synced image in the operators Dockerfile
  Dockerfile
Labels: lgtm, size/XS, kind/chore, cla: yes, area/keda-manager

#469 Change enable and disable to add and delete in the Keda repo
  docs/contributor/01-20-extend-ui.md
  docs/contributor/04-20-lifecycle-management.md
  examples/redis-scaler/README.md
Labels: lgtm, size/S, cla: yes
