Repository kyma-project/keda-manager, pull requests merged in 2025-01, with the labels that each got.

#563 Remove unused release step
  .github/workflows/create-release.yaml
Labels: lgtm, area/ci, size/S, kind/cleanup, cla: yes

#562 Bump Keda to 2.16.1
  config/ui-extensions/scaledobjects/list
  controllers/keda_controller_rbacs.go
  keda.yaml
  sec-scanners-config.yaml
Labels: size/L, cla: yes

#566 Bump actions used for kyma terraforming in integration tests
  .github/workflows/_integration-tests.yaml
Labels: area/ci, kind/chore

#570 Fix a link
  examples/redis-scaler/README.md
Labels: size/XS, cla: yes
