Repository kyma-project/keda-manager, pull requests merged in 2025-03, with the labels that each got.

#585 Migrate sec scanners
  sec-scanners-config.yaml
Labels: size/S

#586 fix build job permissions
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: lgtm, area/ci, size/XS

#587 Enable `prometheus` metrics
  Makefile
  hack/keda_values.yaml
  keda.yaml
Labels: size/M, area/keda-manager, kind/enhancement

#595 Update codeowners
  CODEOWNERS
Labels: area/ci, kind/enhancement
